spawn:
  x: -2.0
  y: -0.5
  yaw: 0.0

north_west_room:
  x: -6.2
  y: 3.4
  yaw: 0.0

north_center_room:
  x: 1.05
  y: 3.1
  yaw: 0.0

north_east_room:
  x: 4.8
  y: 3.0
  yaw: 0.0

hallway_center:
  x: 5.6
  y: -1.0
  yaw: 0.0

south_east_room:
  x: -6.3
  y: -1.8
  yaw: 0.0

south_west_room:
  x: 5.7
  y: -4.15
  yaw: 0.0
